set(CMAKE_SYSTEM_NAME Generic-ELF)
set(CMAKE_SYSTEM_PROCESSOR ARM)
set(CMAKE_C_COMPILER_ID ARMCC)
set(CMAKE_CXX_COMPILER_ID ARMCC)

# TARGET_TRIPLET
set(TARGET_TRIPLET "arm-none-eabi")

IF(NOT TOOLCHAIN_DIR)
    if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
        message(FATAL_ERROR "CMAKE_HOST_SYSTEM_PROCESSOR unknown")
    endif()

    set(TOOLCHAINS_STORAGE_DIR "${CMAKE_SOURCE_DIR}/toolchain")
    set(ARM_TOOLCHAIN_NAME "arm-gnu-toolchain-14.2.rel1-${CMAKE_HOST_SYSTEM_PROCESSOR}-${TARGET_TRIPLET}")
    if (${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL "x86_64")
        set(ARM_TOOLCHAIN_HASH)
    elseif(${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL "aarch64")
        set(ARM_TOOLCHAIN_HASH)
    else()
        message(FATAL_ERROR "Can't download ARM toolchain for host architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
    endif()

    set(ARM_TOOLCHAIN_URL "https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/${ARM_TOOLCHAIN_NAME}.tar.xz")
    if (NOT EXISTS ${TOOLCHAINS_STORAGE_DIR}/${ARM_TOOLCHAIN_NAME}.tar.xz)
        message(STATUS "Downloading Arm GCC toolchain ${ARM_TOOLCHAIN_URL} to: ${TOOLCHAINS_STORAGE_DIR}")
        file(DOWNLOAD ${ARM_TOOLCHAIN_URL} ${TOOLCHAINS_STORAGE_DIR}/${ARM_TOOLCHAIN_NAME}.tar.xz
            # EXPECTED_HASH SHA256=62a63b981fe391a9cbad7ef51b17e49aeaa3e7b0d029b36ca1e9c3b2a9b78823
            SHOW_PROGRESS)
    endif()
    if(NOT EXISTS ${TOOLCHAINS_STORAGE_DIR}/${ARM_TOOLCHAIN_NAME}) # prevent repeated extractions
        file(ARCHIVE_EXTRACT INPUT ${TOOLCHAINS_STORAGE_DIR}/${ARM_TOOLCHAIN_NAME}.tar.xz
            DESTINATION ${TOOLCHAINS_STORAGE_DIR})
    endif()
    set(TOOLCHAIN_DIR "${TOOLCHAINS_STORAGE_DIR}/${ARM_TOOLCHAIN_NAME}")
ENDIF()

MESSAGE(STATUS "TOOLCHAIN_DIR: " ${TOOLCHAIN_DIR})

set(TOOLCHAIN_BIN_DIR ${TOOLCHAIN_DIR}/bin)
set(CMAKE_C_COMPILER ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_BIN_DIR}/${TARGET_TRIPLET}-gcc)

set(COMMON_COMPILER_FLAGS "-mthumb -mcpu=cortex-m4 -mfloat-abi=soft -fno-common -ffunction-sections -fdata-sections")
SET(CMAKE_ASM_FLAGS "${COMMON_COMPILER_FLAGS}")
SET(CMAKE_C_FLAGS "${COMMON_COMPILER_FLAGS}")
SET(CMAKE_CXX_FLAGS "${COMMON_COMPILER_FLAGS}")
SET(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
